// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.confluentcloud.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class FlinkMaterializedTableColumnColumnsComputedArgs extends com.pulumi.resources.ResourceArgs {

    public static final FlinkMaterializedTableColumnColumnsComputedArgs Empty = new FlinkMaterializedTableColumnColumnsComputedArgs();

    /**
     * Comment for the computed column.
     * 
     */
    @Import(name="columnComputedComment")
    private @Nullable Output<String> columnComputedComment;

    /**
     * @return Comment for the computed column.
     * 
     */
    public Optional<Output<String>> columnComputedComment() {
        return Optional.ofNullable(this.columnComputedComment);
    }

    /**
     * Expression of the computed column.
     * 
     */
    @Import(name="columnComputedExpression")
    private @Nullable Output<String> columnComputedExpression;

    /**
     * @return Expression of the computed column.
     * 
     */
    public Optional<Output<String>> columnComputedExpression() {
        return Optional.ofNullable(this.columnComputedExpression);
    }

    /**
     * Kind of the computed column.
     * 
     */
    @Import(name="columnComputedKind")
    private @Nullable Output<String> columnComputedKind;

    /**
     * @return Kind of the computed column.
     * 
     */
    public Optional<Output<String>> columnComputedKind() {
        return Optional.ofNullable(this.columnComputedKind);
    }

    /**
     * Name of the computed column.
     * 
     */
    @Import(name="columnComputedName")
    private @Nullable Output<String> columnComputedName;

    /**
     * @return Name of the computed column.
     * 
     */
    public Optional<Output<String>> columnComputedName() {
        return Optional.ofNullable(this.columnComputedName);
    }

    /**
     * Type of the computed column.
     * 
     */
    @Import(name="columnComputedType")
    private @Nullable Output<String> columnComputedType;

    /**
     * @return Type of the computed column.
     * 
     */
    public Optional<Output<String>> columnComputedType() {
        return Optional.ofNullable(this.columnComputedType);
    }

    /**
     * Whether the computed column is virtual. Defaults to `false`.
     * 
     */
    @Import(name="columnComputedVirtual")
    private @Nullable Output<Boolean> columnComputedVirtual;

    /**
     * @return Whether the computed column is virtual. Defaults to `false`.
     * 
     */
    public Optional<Output<Boolean>> columnComputedVirtual() {
        return Optional.ofNullable(this.columnComputedVirtual);
    }

    private FlinkMaterializedTableColumnColumnsComputedArgs() {}

    private FlinkMaterializedTableColumnColumnsComputedArgs(FlinkMaterializedTableColumnColumnsComputedArgs $) {
        this.columnComputedComment = $.columnComputedComment;
        this.columnComputedExpression = $.columnComputedExpression;
        this.columnComputedKind = $.columnComputedKind;
        this.columnComputedName = $.columnComputedName;
        this.columnComputedType = $.columnComputedType;
        this.columnComputedVirtual = $.columnComputedVirtual;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(FlinkMaterializedTableColumnColumnsComputedArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private FlinkMaterializedTableColumnColumnsComputedArgs $;

        public Builder() {
            $ = new FlinkMaterializedTableColumnColumnsComputedArgs();
        }

        public Builder(FlinkMaterializedTableColumnColumnsComputedArgs defaults) {
            $ = new FlinkMaterializedTableColumnColumnsComputedArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param columnComputedComment Comment for the computed column.
         * 
         * @return builder
         * 
         */
        public Builder columnComputedComment(@Nullable Output<String> columnComputedComment) {
            $.columnComputedComment = columnComputedComment;
            return this;
        }

        /**
         * @param columnComputedComment Comment for the computed column.
         * 
         * @return builder
         * 
         */
        public Builder columnComputedComment(String columnComputedComment) {
            return columnComputedComment(Output.of(columnComputedComment));
        }

        /**
         * @param columnComputedExpression Expression of the computed column.
         * 
         * @return builder
         * 
         */
        public Builder columnComputedExpression(@Nullable Output<String> columnComputedExpression) {
            $.columnComputedExpression = columnComputedExpression;
            return this;
        }

        /**
         * @param columnComputedExpression Expression of the computed column.
         * 
         * @return builder
         * 
         */
        public Builder columnComputedExpression(String columnComputedExpression) {
            return columnComputedExpression(Output.of(columnComputedExpression));
        }

        /**
         * @param columnComputedKind Kind of the computed column.
         * 
         * @return builder
         * 
         */
        public Builder columnComputedKind(@Nullable Output<String> columnComputedKind) {
            $.columnComputedKind = columnComputedKind;
            return this;
        }

        /**
         * @param columnComputedKind Kind of the computed column.
         * 
         * @return builder
         * 
         */
        public Builder columnComputedKind(String columnComputedKind) {
            return columnComputedKind(Output.of(columnComputedKind));
        }

        /**
         * @param columnComputedName Name of the computed column.
         * 
         * @return builder
         * 
         */
        public Builder columnComputedName(@Nullable Output<String> columnComputedName) {
            $.columnComputedName = columnComputedName;
            return this;
        }

        /**
         * @param columnComputedName Name of the computed column.
         * 
         * @return builder
         * 
         */
        public Builder columnComputedName(String columnComputedName) {
            return columnComputedName(Output.of(columnComputedName));
        }

        /**
         * @param columnComputedType Type of the computed column.
         * 
         * @return builder
         * 
         */
        public Builder columnComputedType(@Nullable Output<String> columnComputedType) {
            $.columnComputedType = columnComputedType;
            return this;
        }

        /**
         * @param columnComputedType Type of the computed column.
         * 
         * @return builder
         * 
         */
        public Builder columnComputedType(String columnComputedType) {
            return columnComputedType(Output.of(columnComputedType));
        }

        /**
         * @param columnComputedVirtual Whether the computed column is virtual. Defaults to `false`.
         * 
         * @return builder
         * 
         */
        public Builder columnComputedVirtual(@Nullable Output<Boolean> columnComputedVirtual) {
            $.columnComputedVirtual = columnComputedVirtual;
            return this;
        }

        /**
         * @param columnComputedVirtual Whether the computed column is virtual. Defaults to `false`.
         * 
         * @return builder
         * 
         */
        public Builder columnComputedVirtual(Boolean columnComputedVirtual) {
            return columnComputedVirtual(Output.of(columnComputedVirtual));
        }

        public FlinkMaterializedTableColumnColumnsComputedArgs build() {
            return $;
        }
    }

}
