// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.confluentcloud.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GatewayAzureEgressPrivateLinkGatewayArgs extends com.pulumi.resources.ResourceArgs {

    public static final GatewayAzureEgressPrivateLinkGatewayArgs Empty = new GatewayAzureEgressPrivateLinkGatewayArgs();

    /**
     * Azure region of the Gateway, for example, `eastus`.
     * 
     */
    @Import(name="region", required=true)
    private Output<String> region;

    /**
     * @return Azure region of the Gateway, for example, `eastus`.
     * 
     */
    public Output<String> region() {
        return this.region;
    }

    /**
     * (Required String) The Azure Subscription ID associated with the Confluent Cloud VPC, for example, `00000000-0000-0000-0000-000000000000`.
     * 
     */
    @Import(name="subscription")
    private @Nullable Output<String> subscription;

    /**
     * @return (Required String) The Azure Subscription ID associated with the Confluent Cloud VPC, for example, `00000000-0000-0000-0000-000000000000`.
     * 
     */
    public Optional<Output<String>> subscription() {
        return Optional.ofNullable(this.subscription);
    }

    private GatewayAzureEgressPrivateLinkGatewayArgs() {}

    private GatewayAzureEgressPrivateLinkGatewayArgs(GatewayAzureEgressPrivateLinkGatewayArgs $) {
        this.region = $.region;
        this.subscription = $.subscription;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GatewayAzureEgressPrivateLinkGatewayArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GatewayAzureEgressPrivateLinkGatewayArgs $;

        public Builder() {
            $ = new GatewayAzureEgressPrivateLinkGatewayArgs();
        }

        public Builder(GatewayAzureEgressPrivateLinkGatewayArgs defaults) {
            $ = new GatewayAzureEgressPrivateLinkGatewayArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param region Azure region of the Gateway, for example, `eastus`.
         * 
         * @return builder
         * 
         */
        public Builder region(Output<String> region) {
            $.region = region;
            return this;
        }

        /**
         * @param region Azure region of the Gateway, for example, `eastus`.
         * 
         * @return builder
         * 
         */
        public Builder region(String region) {
            return region(Output.of(region));
        }

        /**
         * @param subscription (Required String) The Azure Subscription ID associated with the Confluent Cloud VPC, for example, `00000000-0000-0000-0000-000000000000`.
         * 
         * @return builder
         * 
         */
        public Builder subscription(@Nullable Output<String> subscription) {
            $.subscription = subscription;
            return this;
        }

        /**
         * @param subscription (Required String) The Azure Subscription ID associated with the Confluent Cloud VPC, for example, `00000000-0000-0000-0000-000000000000`.
         * 
         * @return builder
         * 
         */
        public Builder subscription(String subscription) {
            return subscription(Output.of(subscription));
        }

        public GatewayAzureEgressPrivateLinkGatewayArgs build() {
            if ($.region == null) {
                throw new MissingRequiredPropertyException("GatewayAzureEgressPrivateLinkGatewayArgs", "region");
            }
            return $;
        }
    }

}
