// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.confluentcloud.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GatewayAwsEgressPrivateLinkGatewayArgs extends com.pulumi.resources.ResourceArgs {

    public static final GatewayAwsEgressPrivateLinkGatewayArgs Empty = new GatewayAwsEgressPrivateLinkGatewayArgs();

    /**
     * (Required String) The principal ARN used by the AWS Egress Private Link Gateway, for example, `arn:aws:iam::123456789012:tenant-1-role`.
     * 
     */
    @Import(name="principalArn")
    private @Nullable Output<String> principalArn;

    /**
     * @return (Required String) The principal ARN used by the AWS Egress Private Link Gateway, for example, `arn:aws:iam::123456789012:tenant-1-role`.
     * 
     */
    public Optional<Output<String>> principalArn() {
        return Optional.ofNullable(this.principalArn);
    }

    /**
     * AWS region of the Gateway, for example, `us-east-1`.
     * 
     */
    @Import(name="region", required=true)
    private Output<String> region;

    /**
     * @return AWS region of the Gateway, for example, `us-east-1`.
     * 
     */
    public Output<String> region() {
        return this.region;
    }

    private GatewayAwsEgressPrivateLinkGatewayArgs() {}

    private GatewayAwsEgressPrivateLinkGatewayArgs(GatewayAwsEgressPrivateLinkGatewayArgs $) {
        this.principalArn = $.principalArn;
        this.region = $.region;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GatewayAwsEgressPrivateLinkGatewayArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GatewayAwsEgressPrivateLinkGatewayArgs $;

        public Builder() {
            $ = new GatewayAwsEgressPrivateLinkGatewayArgs();
        }

        public Builder(GatewayAwsEgressPrivateLinkGatewayArgs defaults) {
            $ = new GatewayAwsEgressPrivateLinkGatewayArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param principalArn (Required String) The principal ARN used by the AWS Egress Private Link Gateway, for example, `arn:aws:iam::123456789012:tenant-1-role`.
         * 
         * @return builder
         * 
         */
        public Builder principalArn(@Nullable Output<String> principalArn) {
            $.principalArn = principalArn;
            return this;
        }

        /**
         * @param principalArn (Required String) The principal ARN used by the AWS Egress Private Link Gateway, for example, `arn:aws:iam::123456789012:tenant-1-role`.
         * 
         * @return builder
         * 
         */
        public Builder principalArn(String principalArn) {
            return principalArn(Output.of(principalArn));
        }

        /**
         * @param region AWS region of the Gateway, for example, `us-east-1`.
         * 
         * @return builder
         * 
         */
        public Builder region(Output<String> region) {
            $.region = region;
            return this;
        }

        /**
         * @param region AWS region of the Gateway, for example, `us-east-1`.
         * 
         * @return builder
         * 
         */
        public Builder region(String region) {
            return region(Output.of(region));
        }

        public GatewayAwsEgressPrivateLinkGatewayArgs build() {
            if ($.region == null) {
                throw new MissingRequiredPropertyException("GatewayAwsEgressPrivateLinkGatewayArgs", "region");
            }
            return $;
        }
    }

}
