// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.confluentcloud.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetFlinkConnectionOrganization extends com.pulumi.resources.InvokeArgs {

    public static final GetFlinkConnectionOrganization Empty = new GetFlinkConnectionOrganization();

    /**
     * The ID of the Organization, for example, `1111aaaa-11aa-11aa-11aa-111111aaaaaa`.
     * 
     */
    @Import(name="id", required=true)
    private String id;

    /**
     * @return The ID of the Organization, for example, `1111aaaa-11aa-11aa-11aa-111111aaaaaa`.
     * 
     */
    public String id() {
        return this.id;
    }

    private GetFlinkConnectionOrganization() {}

    private GetFlinkConnectionOrganization(GetFlinkConnectionOrganization $) {
        this.id = $.id;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetFlinkConnectionOrganization defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetFlinkConnectionOrganization $;

        public Builder() {
            $ = new GetFlinkConnectionOrganization();
        }

        public Builder(GetFlinkConnectionOrganization defaults) {
            $ = new GetFlinkConnectionOrganization(Objects.requireNonNull(defaults));
        }

        /**
         * @param id The ID of the Organization, for example, `1111aaaa-11aa-11aa-11aa-111111aaaaaa`.
         * 
         * @return builder
         * 
         */
        public Builder id(String id) {
            $.id = id;
            return this;
        }

        public GetFlinkConnectionOrganization build() {
            if ($.id == null) {
                throw new MissingRequiredPropertyException("GetFlinkConnectionOrganization", "id");
            }
            return $;
        }
    }

}
