// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.confluentcloud.inputs;

import com.pulumi.confluentcloud.inputs.GetGatewaysEnvironmentArgs;
import com.pulumi.confluentcloud.inputs.GetGatewaysFilterArgs;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetGatewaysArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetGatewaysArgs Empty = new GetGatewaysArgs();

    @Import(name="environment", required=true)
    private Output<GetGatewaysEnvironmentArgs> environment;

    public Output<GetGatewaysEnvironmentArgs> environment() {
        return this.environment;
    }

    @Import(name="filter")
    private @Nullable Output<GetGatewaysFilterArgs> filter;

    public Optional<Output<GetGatewaysFilterArgs>> filter() {
        return Optional.ofNullable(this.filter);
    }

    private GetGatewaysArgs() {}

    private GetGatewaysArgs(GetGatewaysArgs $) {
        this.environment = $.environment;
        this.filter = $.filter;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetGatewaysArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetGatewaysArgs $;

        public Builder() {
            $ = new GetGatewaysArgs();
        }

        public Builder(GetGatewaysArgs defaults) {
            $ = new GetGatewaysArgs(Objects.requireNonNull(defaults));
        }

        public Builder environment(Output<GetGatewaysEnvironmentArgs> environment) {
            $.environment = environment;
            return this;
        }

        public Builder environment(GetGatewaysEnvironmentArgs environment) {
            return environment(Output.of(environment));
        }

        public Builder filter(@Nullable Output<GetGatewaysFilterArgs> filter) {
            $.filter = filter;
            return this;
        }

        public Builder filter(GetGatewaysFilterArgs filter) {
            return filter(Output.of(filter));
        }

        public GetGatewaysArgs build() {
            if ($.environment == null) {
                throw new MissingRequiredPropertyException("GetGatewaysArgs", "environment");
            }
            return $;
        }
    }

}
