// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.confluentcloud.inputs;




public final class GetKafkaClusterBasic extends com.pulumi.resources.InvokeArgs {

    public static final GetKafkaClusterBasic Empty = new GetKafkaClusterBasic();

    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private GetKafkaClusterBasic $;

        public Builder() {
            $ = new GetKafkaClusterBasic();
        }
        public GetKafkaClusterBasic build() {
            return $;
        }
    }

}
