// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.confluentcloud.inputs;

import com.pulumi.confluentcloud.inputs.GetKafkaClustersEnvironmentArgs;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.util.Objects;


public final class GetKafkaClustersArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetKafkaClustersArgs Empty = new GetKafkaClustersArgs();

    /**
     * (Required Object) exports the following attributes:
     * 
     */
    @Import(name="environment", required=true)
    private Output<GetKafkaClustersEnvironmentArgs> environment;

    /**
     * @return (Required Object) exports the following attributes:
     * 
     */
    public Output<GetKafkaClustersEnvironmentArgs> environment() {
        return this.environment;
    }

    private GetKafkaClustersArgs() {}

    private GetKafkaClustersArgs(GetKafkaClustersArgs $) {
        this.environment = $.environment;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetKafkaClustersArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetKafkaClustersArgs $;

        public Builder() {
            $ = new GetKafkaClustersArgs();
        }

        public Builder(GetKafkaClustersArgs defaults) {
            $ = new GetKafkaClustersArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param environment (Required Object) exports the following attributes:
         * 
         * @return builder
         * 
         */
        public Builder environment(Output<GetKafkaClustersEnvironmentArgs> environment) {
            $.environment = environment;
            return this;
        }

        /**
         * @param environment (Required Object) exports the following attributes:
         * 
         * @return builder
         * 
         */
        public Builder environment(GetKafkaClustersEnvironmentArgs environment) {
            return environment(Output.of(environment));
        }

        public GetKafkaClustersArgs build() {
            if ($.environment == null) {
                throw new MissingRequiredPropertyException("GetKafkaClustersArgs", "environment");
            }
            return $;
        }
    }

}
