// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.confluentcloud.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.util.Objects;


public final class GetKafkaClusterStandardArgs extends com.pulumi.resources.ResourceArgs {

    public static final GetKafkaClusterStandardArgs Empty = new GetKafkaClusterStandardArgs();

    /**
     * (Optional Number) The maximum number of Elastic Confluent Kafka Units (eCKUs) that Kafka clusters should auto-scale to. Kafka clusters with &#34;HIGH&#34; availability must have at least two eCKUs. For more details, see [Maximum eCKU requirements](https://docs.confluent.io/cloud/current/clusters/cluster-types.html#minimum-maximum-ecku-requirements).
     * 
     */
    @Import(name="maxEcku", required=true)
    private Output<Integer> maxEcku;

    /**
     * @return (Optional Number) The maximum number of Elastic Confluent Kafka Units (eCKUs) that Kafka clusters should auto-scale to. Kafka clusters with &#34;HIGH&#34; availability must have at least two eCKUs. For more details, see [Maximum eCKU requirements](https://docs.confluent.io/cloud/current/clusters/cluster-types.html#minimum-maximum-ecku-requirements).
     * 
     */
    public Output<Integer> maxEcku() {
        return this.maxEcku;
    }

    private GetKafkaClusterStandardArgs() {}

    private GetKafkaClusterStandardArgs(GetKafkaClusterStandardArgs $) {
        this.maxEcku = $.maxEcku;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetKafkaClusterStandardArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetKafkaClusterStandardArgs $;

        public Builder() {
            $ = new GetKafkaClusterStandardArgs();
        }

        public Builder(GetKafkaClusterStandardArgs defaults) {
            $ = new GetKafkaClusterStandardArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param maxEcku (Optional Number) The maximum number of Elastic Confluent Kafka Units (eCKUs) that Kafka clusters should auto-scale to. Kafka clusters with &#34;HIGH&#34; availability must have at least two eCKUs. For more details, see [Maximum eCKU requirements](https://docs.confluent.io/cloud/current/clusters/cluster-types.html#minimum-maximum-ecku-requirements).
         * 
         * @return builder
         * 
         */
        public Builder maxEcku(Output<Integer> maxEcku) {
            $.maxEcku = maxEcku;
            return this;
        }

        /**
         * @param maxEcku (Optional Number) The maximum number of Elastic Confluent Kafka Units (eCKUs) that Kafka clusters should auto-scale to. Kafka clusters with &#34;HIGH&#34; availability must have at least two eCKUs. For more details, see [Maximum eCKU requirements](https://docs.confluent.io/cloud/current/clusters/cluster-types.html#minimum-maximum-ecku-requirements).
         * 
         * @return builder
         * 
         */
        public Builder maxEcku(Integer maxEcku) {
            return maxEcku(Output.of(maxEcku));
        }

        public GetKafkaClusterStandardArgs build() {
            if ($.maxEcku == null) {
                throw new MissingRequiredPropertyException("GetKafkaClusterStandardArgs", "maxEcku");
            }
            return $;
        }
    }

}
