// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.confluentcloud.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetRtceTopicKafkaClusterArgs extends com.pulumi.resources.ResourceArgs {

    public static final GetRtceTopicKafkaClusterArgs Empty = new GetRtceTopicKafkaClusterArgs();

    /**
     * The ID of the Kafka Cluster, for example, `lkc-abc123`.
     * 
     */
    @Import(name="id", required=true)
    private Output<String> id;

    /**
     * @return The ID of the Kafka Cluster, for example, `lkc-abc123`.
     * 
     */
    public Output<String> id() {
        return this.id;
    }

    private GetRtceTopicKafkaClusterArgs() {}

    private GetRtceTopicKafkaClusterArgs(GetRtceTopicKafkaClusterArgs $) {
        this.id = $.id;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetRtceTopicKafkaClusterArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetRtceTopicKafkaClusterArgs $;

        public Builder() {
            $ = new GetRtceTopicKafkaClusterArgs();
        }

        public Builder(GetRtceTopicKafkaClusterArgs defaults) {
            $ = new GetRtceTopicKafkaClusterArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param id The ID of the Kafka Cluster, for example, `lkc-abc123`.
         * 
         * @return builder
         * 
         */
        public Builder id(Output<String> id) {
            $.id = id;
            return this;
        }

        /**
         * @param id The ID of the Kafka Cluster, for example, `lkc-abc123`.
         * 
         * @return builder
         * 
         */
        public Builder id(String id) {
            return id(Output.of(id));
        }

        public GetRtceTopicKafkaClusterArgs build() {
            if ($.id == null) {
                throw new MissingRequiredPropertyException("GetRtceTopicKafkaClusterArgs", "id");
            }
            return $;
        }
    }

}
