// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.confluentcloud.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Integer;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class KafkaClusterStandardArgs extends com.pulumi.resources.ResourceArgs {

    public static final KafkaClusterStandardArgs Empty = new KafkaClusterStandardArgs();

    /**
     * The maximum number of Elastic Confluent Kafka Units (eCKUs) that Kafka clusters should auto-scale to. Kafka clusters with &#34;HIGH&#34; availability must have at least two eCKUs.
     * 
     */
    @Import(name="maxEcku")
    private @Nullable Output<Integer> maxEcku;

    /**
     * @return The maximum number of Elastic Confluent Kafka Units (eCKUs) that Kafka clusters should auto-scale to. Kafka clusters with &#34;HIGH&#34; availability must have at least two eCKUs.
     * 
     */
    public Optional<Output<Integer>> maxEcku() {
        return Optional.ofNullable(this.maxEcku);
    }

    private KafkaClusterStandardArgs() {}

    private KafkaClusterStandardArgs(KafkaClusterStandardArgs $) {
        this.maxEcku = $.maxEcku;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(KafkaClusterStandardArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private KafkaClusterStandardArgs $;

        public Builder() {
            $ = new KafkaClusterStandardArgs();
        }

        public Builder(KafkaClusterStandardArgs defaults) {
            $ = new KafkaClusterStandardArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param maxEcku The maximum number of Elastic Confluent Kafka Units (eCKUs) that Kafka clusters should auto-scale to. Kafka clusters with &#34;HIGH&#34; availability must have at least two eCKUs.
         * 
         * @return builder
         * 
         */
        public Builder maxEcku(@Nullable Output<Integer> maxEcku) {
            $.maxEcku = maxEcku;
            return this;
        }

        /**
         * @param maxEcku The maximum number of Elastic Confluent Kafka Units (eCKUs) that Kafka clusters should auto-scale to. Kafka clusters with &#34;HIGH&#34; availability must have at least two eCKUs.
         * 
         * @return builder
         * 
         */
        public Builder maxEcku(Integer maxEcku) {
            return maxEcku(Output.of(maxEcku));
        }

        public KafkaClusterStandardArgs build() {
            return $;
        }
    }

}
