// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.confluentcloud.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class NetworkGcpArgs extends com.pulumi.resources.ResourceArgs {

    public static final NetworkGcpArgs Empty = new NetworkGcpArgs();

    /**
     * (Optional Map) The mapping of zones to Private Service Connect Service Attachments if available. Keys are zones and values are [GCP Private Service Connect service attachment](https://cloud.google.com/vpc/docs/configure-private-service-connect-producer#api_7).
     * 
     */
    @Import(name="privateServiceConnectServiceAttachments")
    private @Nullable Output<Map<String,String>> privateServiceConnectServiceAttachments;

    /**
     * @return (Optional Map) The mapping of zones to Private Service Connect Service Attachments if available. Keys are zones and values are [GCP Private Service Connect service attachment](https://cloud.google.com/vpc/docs/configure-private-service-connect-producer#api_7).
     * 
     */
    public Optional<Output<Map<String,String>>> privateServiceConnectServiceAttachments() {
        return Optional.ofNullable(this.privateServiceConnectServiceAttachments);
    }

    /**
     * (Required String) The GCP Project ID associated with the Confluent Cloud VPC.
     * 
     */
    @Import(name="project")
    private @Nullable Output<String> project;

    /**
     * @return (Required String) The GCP Project ID associated with the Confluent Cloud VPC.
     * 
     */
    public Optional<Output<String>> project() {
        return Optional.ofNullable(this.project);
    }

    /**
     * (Required String) The network name of the Confluent Cloud VPC.
     * 
     */
    @Import(name="vpcNetwork")
    private @Nullable Output<String> vpcNetwork;

    /**
     * @return (Required String) The network name of the Confluent Cloud VPC.
     * 
     */
    public Optional<Output<String>> vpcNetwork() {
        return Optional.ofNullable(this.vpcNetwork);
    }

    private NetworkGcpArgs() {}

    private NetworkGcpArgs(NetworkGcpArgs $) {
        this.privateServiceConnectServiceAttachments = $.privateServiceConnectServiceAttachments;
        this.project = $.project;
        this.vpcNetwork = $.vpcNetwork;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(NetworkGcpArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private NetworkGcpArgs $;

        public Builder() {
            $ = new NetworkGcpArgs();
        }

        public Builder(NetworkGcpArgs defaults) {
            $ = new NetworkGcpArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param privateServiceConnectServiceAttachments (Optional Map) The mapping of zones to Private Service Connect Service Attachments if available. Keys are zones and values are [GCP Private Service Connect service attachment](https://cloud.google.com/vpc/docs/configure-private-service-connect-producer#api_7).
         * 
         * @return builder
         * 
         */
        public Builder privateServiceConnectServiceAttachments(@Nullable Output<Map<String,String>> privateServiceConnectServiceAttachments) {
            $.privateServiceConnectServiceAttachments = privateServiceConnectServiceAttachments;
            return this;
        }

        /**
         * @param privateServiceConnectServiceAttachments (Optional Map) The mapping of zones to Private Service Connect Service Attachments if available. Keys are zones and values are [GCP Private Service Connect service attachment](https://cloud.google.com/vpc/docs/configure-private-service-connect-producer#api_7).
         * 
         * @return builder
         * 
         */
        public Builder privateServiceConnectServiceAttachments(Map<String,String> privateServiceConnectServiceAttachments) {
            return privateServiceConnectServiceAttachments(Output.of(privateServiceConnectServiceAttachments));
        }

        /**
         * @param project (Required String) The GCP Project ID associated with the Confluent Cloud VPC.
         * 
         * @return builder
         * 
         */
        public Builder project(@Nullable Output<String> project) {
            $.project = project;
            return this;
        }

        /**
         * @param project (Required String) The GCP Project ID associated with the Confluent Cloud VPC.
         * 
         * @return builder
         * 
         */
        public Builder project(String project) {
            return project(Output.of(project));
        }

        /**
         * @param vpcNetwork (Required String) The network name of the Confluent Cloud VPC.
         * 
         * @return builder
         * 
         */
        public Builder vpcNetwork(@Nullable Output<String> vpcNetwork) {
            $.vpcNetwork = vpcNetwork;
            return this;
        }

        /**
         * @param vpcNetwork (Required String) The network name of the Confluent Cloud VPC.
         * 
         * @return builder
         * 
         */
        public Builder vpcNetwork(String vpcNetwork) {
            return vpcNetwork(Output.of(vpcNetwork));
        }

        public NetworkGcpArgs build() {
            return $;
        }
    }

}
