// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.confluentcloud.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class TagSchemaRegistryClusterArgs extends com.pulumi.resources.ResourceArgs {

    public static final TagSchemaRegistryClusterArgs Empty = new TagSchemaRegistryClusterArgs();

    /**
     * The ID of the Schema Registry cluster, for example, `lsrc-abc123`.
     * 
     */
    @Import(name="id", required=true)
    private Output<String> id;

    /**
     * @return The ID of the Schema Registry cluster, for example, `lsrc-abc123`.
     * 
     */
    public Output<String> id() {
        return this.id;
    }

    private TagSchemaRegistryClusterArgs() {}

    private TagSchemaRegistryClusterArgs(TagSchemaRegistryClusterArgs $) {
        this.id = $.id;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(TagSchemaRegistryClusterArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private TagSchemaRegistryClusterArgs $;

        public Builder() {
            $ = new TagSchemaRegistryClusterArgs();
        }

        public Builder(TagSchemaRegistryClusterArgs defaults) {
            $ = new TagSchemaRegistryClusterArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param id The ID of the Schema Registry cluster, for example, `lsrc-abc123`.
         * 
         * @return builder
         * 
         */
        public Builder id(Output<String> id) {
            $.id = id;
            return this;
        }

        /**
         * @param id The ID of the Schema Registry cluster, for example, `lsrc-abc123`.
         * 
         * @return builder
         * 
         */
        public Builder id(String id) {
            return id(Output.of(id));
        }

        public TagSchemaRegistryClusterArgs build() {
            if ($.id == null) {
                throw new MissingRequiredPropertyException("TagSchemaRegistryClusterArgs", "id");
            }
            return $;
        }
    }

}
