provider: confluentcloud
lint: false
major-version: 2
providerDefaultBranch: main
esc:
    enabled: true
env:
    CONFLUENT_CLOUD_API_KEY: ${{ secrets.CONFLUENT_CLOUD_API_KEY }}
    CONFLUENT_CLOUD_API_SECRET: ${{ secrets.CONFLUENT_CLOUD_API_SECRET }}
upstream-provider-repo: terraform-provider-confluent
makeTemplate: bridged
team: ecosystem
pulumiConvert: 1
registryDocs: true
