// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.ConfluentCloud
{
    public static class GetProviderIntegrationAuthorization
    {
        public static Task<GetProviderIntegrationAuthorizationResult> InvokeAsync(GetProviderIntegrationAuthorizationArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetProviderIntegrationAuthorizationResult>("confluentcloud:index/getProviderIntegrationAuthorization:getProviderIntegrationAuthorization", args ?? new GetProviderIntegrationAuthorizationArgs(), options.WithDefaults());

        public static Output<GetProviderIntegrationAuthorizationResult> Invoke(GetProviderIntegrationAuthorizationInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetProviderIntegrationAuthorizationResult>("confluentcloud:index/getProviderIntegrationAuthorization:getProviderIntegrationAuthorization", args ?? new GetProviderIntegrationAuthorizationInvokeArgs(), options.WithDefaults());

        public static Output<GetProviderIntegrationAuthorizationResult> Invoke(GetProviderIntegrationAuthorizationInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetProviderIntegrationAuthorizationResult>("confluentcloud:index/getProviderIntegrationAuthorization:getProviderIntegrationAuthorization", args ?? new GetProviderIntegrationAuthorizationInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetProviderIntegrationAuthorizationArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// (Required Configuration Block) supports the following:
        /// </summary>
        [Input("environment", required: true)]
        public Inputs.GetProviderIntegrationAuthorizationEnvironmentArgs Environment { get; set; } = null!;

        /// <summary>
        /// The ID of the Provider Integration Authorization, for example, `cspi-4xg0q`.
        /// </summary>
        [Input("id", required: true)]
        public string Id { get; set; } = null!;

        public GetProviderIntegrationAuthorizationArgs()
        {
        }
        public static new GetProviderIntegrationAuthorizationArgs Empty => new GetProviderIntegrationAuthorizationArgs();
    }

    public sealed class GetProviderIntegrationAuthorizationInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// (Required Configuration Block) supports the following:
        /// </summary>
        [Input("environment", required: true)]
        public Input<Inputs.GetProviderIntegrationAuthorizationEnvironmentInputArgs> Environment { get; set; } = null!;

        /// <summary>
        /// The ID of the Provider Integration Authorization, for example, `cspi-4xg0q`.
        /// </summary>
        [Input("id", required: true)]
        public Input<string> Id { get; set; } = null!;

        public GetProviderIntegrationAuthorizationInvokeArgs()
        {
        }
        public static new GetProviderIntegrationAuthorizationInvokeArgs Empty => new GetProviderIntegrationAuthorizationInvokeArgs();
    }


    [OutputType]
    public sealed class GetProviderIntegrationAuthorizationResult
    {
        /// <summary>
        /// (Optional Configuration Block) Azure-specific configuration details. Present for Azure integrations. It supports the following:
        /// </summary>
        public readonly ImmutableArray<Outputs.GetProviderIntegrationAuthorizationAzureResult> Azures;
        /// <summary>
        /// (Required Configuration Block) supports the following:
        /// </summary>
        public readonly Outputs.GetProviderIntegrationAuthorizationEnvironmentResult Environment;
        /// <summary>
        /// (Optional Configuration Block) GCP-specific configuration details. Present for GCP integrations. It supports the following:
        /// </summary>
        public readonly ImmutableArray<Outputs.GetProviderIntegrationAuthorizationGcpResult> Gcps;
        /// <summary>
        /// (Required String) The ID of the Environment that the Provider Integration belongs to, for example, `env-abc123`.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// (Required String) The ID of the provider integration.
        /// </summary>
        public readonly string ProviderIntegrationId;

        [OutputConstructor]
        private GetProviderIntegrationAuthorizationResult(
            ImmutableArray<Outputs.GetProviderIntegrationAuthorizationAzureResult> azures,

            Outputs.GetProviderIntegrationAuthorizationEnvironmentResult environment,

            ImmutableArray<Outputs.GetProviderIntegrationAuthorizationGcpResult> gcps,

            string id,

            string providerIntegrationId)
        {
            Azures = azures;
            Environment = environment;
            Gcps = gcps;
            Id = id;
            ProviderIntegrationId = providerIntegrationId;
        }
    }
}
