// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.confluentcloud.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class AccessPointAwsIngressPrivateLinkEndpoint {
    /**
     * @return (Required String) DNS domain name used to configure the Private Hosted Zone for the Access Point, for example, `ap123abc.us-west-2.aws.accesspoint.confluent.cloud`.
     * 
     */
    private @Nullable String dnsDomain;
    /**
     * @return ID of a VPC Endpoint that will be connected to the VPC Endpoint service, for example, `vpce-00000000000000000`.
     * 
     */
    private String vpcEndpointId;
    /**
     * @return (Required String) ID of the Confluent Cloud VPC Endpoint service used for PrivateLink, for example, `com.amazonaws.vpce.us-west-2.vpce-svc-00000000000000000`.
     * 
     */
    private @Nullable String vpcEndpointServiceName;

    private AccessPointAwsIngressPrivateLinkEndpoint() {}
    /**
     * @return (Required String) DNS domain name used to configure the Private Hosted Zone for the Access Point, for example, `ap123abc.us-west-2.aws.accesspoint.confluent.cloud`.
     * 
     */
    public Optional<String> dnsDomain() {
        return Optional.ofNullable(this.dnsDomain);
    }
    /**
     * @return ID of a VPC Endpoint that will be connected to the VPC Endpoint service, for example, `vpce-00000000000000000`.
     * 
     */
    public String vpcEndpointId() {
        return this.vpcEndpointId;
    }
    /**
     * @return (Required String) ID of the Confluent Cloud VPC Endpoint service used for PrivateLink, for example, `com.amazonaws.vpce.us-west-2.vpce-svc-00000000000000000`.
     * 
     */
    public Optional<String> vpcEndpointServiceName() {
        return Optional.ofNullable(this.vpcEndpointServiceName);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(AccessPointAwsIngressPrivateLinkEndpoint defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String dnsDomain;
        private String vpcEndpointId;
        private @Nullable String vpcEndpointServiceName;
        public Builder() {}
        public Builder(AccessPointAwsIngressPrivateLinkEndpoint defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.dnsDomain = defaults.dnsDomain;
    	      this.vpcEndpointId = defaults.vpcEndpointId;
    	      this.vpcEndpointServiceName = defaults.vpcEndpointServiceName;
        }

        @CustomType.Setter
        public Builder dnsDomain(@Nullable String dnsDomain) {

            this.dnsDomain = dnsDomain;
            return this;
        }
        @CustomType.Setter
        public Builder vpcEndpointId(String vpcEndpointId) {
            if (vpcEndpointId == null) {
              throw new MissingRequiredPropertyException("AccessPointAwsIngressPrivateLinkEndpoint", "vpcEndpointId");
            }
            this.vpcEndpointId = vpcEndpointId;
            return this;
        }
        @CustomType.Setter
        public Builder vpcEndpointServiceName(@Nullable String vpcEndpointServiceName) {

            this.vpcEndpointServiceName = vpcEndpointServiceName;
            return this;
        }
        public AccessPointAwsIngressPrivateLinkEndpoint build() {
            final var _resultValue = new AccessPointAwsIngressPrivateLinkEndpoint();
            _resultValue.dnsDomain = dnsDomain;
            _resultValue.vpcEndpointId = vpcEndpointId;
            _resultValue.vpcEndpointServiceName = vpcEndpointServiceName;
            return _resultValue;
        }
    }
}
