// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.confluentcloud.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class CatalogIntegrationKafkaCluster {
    /**
     * @return The ID of the Kafka cluster, for example, `lkc-abc123`.
     * 
     */
    private String id;

    private CatalogIntegrationKafkaCluster() {}
    /**
     * @return The ID of the Kafka cluster, for example, `lkc-abc123`.
     * 
     */
    public String id() {
        return this.id;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(CatalogIntegrationKafkaCluster defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String id;
        public Builder() {}
        public Builder(CatalogIntegrationKafkaCluster defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.id = defaults.id;
        }

        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("CatalogIntegrationKafkaCluster", "id");
            }
            this.id = id;
            return this;
        }
        public CatalogIntegrationKafkaCluster build() {
            final var _resultValue = new CatalogIntegrationKafkaCluster();
            _resultValue.id = id;
            return _resultValue;
        }
    }
}
