// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.confluentcloud.outputs;

import com.pulumi.confluentcloud.outputs.GetSubjectConfigCredentials;
import com.pulumi.confluentcloud.outputs.GetSubjectConfigSchemaRegistryCluster;
import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetSubjectConfigResult {
    /**
     * @return (Optional String) The subject name that this subject is an alias for.
     * 
     */
    private String alias;
    /**
     * @return (Optional String) The Compatibility Group of the specified subject.
     * 
     */
    private String compatibilityGroup;
    /**
     * @return (Optional String) The Compatibility Level of the specified subject. Accepted values are: `BACKWARD`, `BACKWARD_TRANSITIVE`, `FORWARD`, `FORWARD_TRANSITIVE`, `FULL`, `FULL_TRANSITIVE`, and `NONE`. See the [Compatibility Types](https://docs.confluent.io/platform/current/schema-registry/avro.html#compatibility-types) for more details.
     * 
     */
    private String compatibilityLevel;
    private @Nullable GetSubjectConfigCredentials credentials;
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    private String id;
    /**
     * @return (Optional Boolean) Whether schemas are automatically normalized when registered or passed during lookups.
     * 
     */
    private Boolean normalize;
    private @Nullable String restEndpoint;
    private @Nullable GetSubjectConfigSchemaRegistryCluster schemaRegistryCluster;
    private String subjectName;

    private GetSubjectConfigResult() {}
    /**
     * @return (Optional String) The subject name that this subject is an alias for.
     * 
     */
    public String alias() {
        return this.alias;
    }
    /**
     * @return (Optional String) The Compatibility Group of the specified subject.
     * 
     */
    public String compatibilityGroup() {
        return this.compatibilityGroup;
    }
    /**
     * @return (Optional String) The Compatibility Level of the specified subject. Accepted values are: `BACKWARD`, `BACKWARD_TRANSITIVE`, `FORWARD`, `FORWARD_TRANSITIVE`, `FULL`, `FULL_TRANSITIVE`, and `NONE`. See the [Compatibility Types](https://docs.confluent.io/platform/current/schema-registry/avro.html#compatibility-types) for more details.
     * 
     */
    public String compatibilityLevel() {
        return this.compatibilityLevel;
    }
    public Optional<GetSubjectConfigCredentials> credentials() {
        return Optional.ofNullable(this.credentials);
    }
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return (Optional Boolean) Whether schemas are automatically normalized when registered or passed during lookups.
     * 
     */
    public Boolean normalize() {
        return this.normalize;
    }
    public Optional<String> restEndpoint() {
        return Optional.ofNullable(this.restEndpoint);
    }
    public Optional<GetSubjectConfigSchemaRegistryCluster> schemaRegistryCluster() {
        return Optional.ofNullable(this.schemaRegistryCluster);
    }
    public String subjectName() {
        return this.subjectName;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetSubjectConfigResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String alias;
        private String compatibilityGroup;
        private String compatibilityLevel;
        private @Nullable GetSubjectConfigCredentials credentials;
        private String id;
        private Boolean normalize;
        private @Nullable String restEndpoint;
        private @Nullable GetSubjectConfigSchemaRegistryCluster schemaRegistryCluster;
        private String subjectName;
        public Builder() {}
        public Builder(GetSubjectConfigResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.alias = defaults.alias;
    	      this.compatibilityGroup = defaults.compatibilityGroup;
    	      this.compatibilityLevel = defaults.compatibilityLevel;
    	      this.credentials = defaults.credentials;
    	      this.id = defaults.id;
    	      this.normalize = defaults.normalize;
    	      this.restEndpoint = defaults.restEndpoint;
    	      this.schemaRegistryCluster = defaults.schemaRegistryCluster;
    	      this.subjectName = defaults.subjectName;
        }

        @CustomType.Setter
        public Builder alias(String alias) {
            if (alias == null) {
              throw new MissingRequiredPropertyException("GetSubjectConfigResult", "alias");
            }
            this.alias = alias;
            return this;
        }
        @CustomType.Setter
        public Builder compatibilityGroup(String compatibilityGroup) {
            if (compatibilityGroup == null) {
              throw new MissingRequiredPropertyException("GetSubjectConfigResult", "compatibilityGroup");
            }
            this.compatibilityGroup = compatibilityGroup;
            return this;
        }
        @CustomType.Setter
        public Builder compatibilityLevel(String compatibilityLevel) {
            if (compatibilityLevel == null) {
              throw new MissingRequiredPropertyException("GetSubjectConfigResult", "compatibilityLevel");
            }
            this.compatibilityLevel = compatibilityLevel;
            return this;
        }
        @CustomType.Setter
        public Builder credentials(@Nullable GetSubjectConfigCredentials credentials) {

            this.credentials = credentials;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetSubjectConfigResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder normalize(Boolean normalize) {
            if (normalize == null) {
              throw new MissingRequiredPropertyException("GetSubjectConfigResult", "normalize");
            }
            this.normalize = normalize;
            return this;
        }
        @CustomType.Setter
        public Builder restEndpoint(@Nullable String restEndpoint) {

            this.restEndpoint = restEndpoint;
            return this;
        }
        @CustomType.Setter
        public Builder schemaRegistryCluster(@Nullable GetSubjectConfigSchemaRegistryCluster schemaRegistryCluster) {

            this.schemaRegistryCluster = schemaRegistryCluster;
            return this;
        }
        @CustomType.Setter
        public Builder subjectName(String subjectName) {
            if (subjectName == null) {
              throw new MissingRequiredPropertyException("GetSubjectConfigResult", "subjectName");
            }
            this.subjectName = subjectName;
            return this;
        }
        public GetSubjectConfigResult build() {
            final var _resultValue = new GetSubjectConfigResult();
            _resultValue.alias = alias;
            _resultValue.compatibilityGroup = compatibilityGroup;
            _resultValue.compatibilityLevel = compatibilityLevel;
            _resultValue.credentials = credentials;
            _resultValue.id = id;
            _resultValue.normalize = normalize;
            _resultValue.restEndpoint = restEndpoint;
            _resultValue.schemaRegistryCluster = schemaRegistryCluster;
            _resultValue.subjectName = subjectName;
            return _resultValue;
        }
    }
}
