// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.ConfluentCloud.Outputs
{

    [OutputType]
    public sealed class BusinessMetadataBindingSchemaRegistryCluster
    {
        /// <summary>
        /// The ID of the Schema Registry cluster, for example, `lsrc-abc123`.
        /// </summary>
        public readonly string Id;

        [OutputConstructor]
        private BusinessMetadataBindingSchemaRegistryCluster(string id)
        {
            Id = id;
        }
    }
}
