// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.ConfluentCloud.Outputs
{

    [OutputType]
    public sealed class FlinkMaterializedTableColumnColumnsComputed
    {
        /// <summary>
        /// Comment for the computed column.
        /// </summary>
        public readonly string? ColumnComputedComment;
        /// <summary>
        /// Expression of the computed column.
        /// </summary>
        public readonly string? ColumnComputedExpression;
        /// <summary>
        /// Kind of the computed column.
        /// </summary>
        public readonly string? ColumnComputedKind;
        /// <summary>
        /// Name of the computed column.
        /// </summary>
        public readonly string? ColumnComputedName;
        /// <summary>
        /// Type of the computed column.
        /// </summary>
        public readonly string? ColumnComputedType;
        /// <summary>
        /// Whether the computed column is virtual. Defaults to `False`.
        /// </summary>
        public readonly bool? ColumnComputedVirtual;

        [OutputConstructor]
        private FlinkMaterializedTableColumnColumnsComputed(
            string? columnComputedComment,

            string? columnComputedExpression,

            string? columnComputedKind,

            string? columnComputedName,

            string? columnComputedType,

            bool? columnComputedVirtual)
        {
            ColumnComputedComment = columnComputedComment;
            ColumnComputedExpression = columnComputedExpression;
            ColumnComputedKind = columnComputedKind;
            ColumnComputedName = columnComputedName;
            ColumnComputedType = columnComputedType;
            ColumnComputedVirtual = columnComputedVirtual;
        }
    }
}
