// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.ConfluentCloud.Outputs
{

    [OutputType]
    public sealed class SchemaRegistryClusterConfigCredentials
    {
        /// <summary>
        /// The Schema Registry API Key.
        /// </summary>
        public readonly string Key;
        /// <summary>
        /// The Schema Registry API Secret.
        /// 
        /// &gt; **Note:** A Schema Registry API key consists of a key and a secret. Schema Registry API keys are required to interact with Schema Registry clusters in Confluent Cloud. Each Schema Registry API key is valid for one specific Schema Registry cluster.
        /// 
        /// &gt; **Note:** Use Option #2 to simplify the key rotation process. When using Option #1, to rotate a Schema Registry API key, create a new Schema Registry API key, update the `Credentials` block in all configuration files to use the new Schema Registry API key, run `pulumi up -target="confluent_schema_registry_cluster_config.orders"`, and remove the old Schema Registry API key. Alternatively, in case the old Schema Registry API Key was deleted already, you might need to run `pulumi preview -refresh=false -target="confluent_schema_registry_cluster_config.orders" -out=rotate-schema-registry-api-key` and `pulumi up rotate-schema-registry-api-key` instead.
        /// 
        /// !&gt; **Warning:** Use Option #2 to avoid exposing sensitive `Credentials` value in a state file. When using Option #1, Terraform doesn't encrypt the sensitive `Credentials` value of the `confluentcloud.SchemaRegistryClusterConfig` resource, so you must keep your state file secure to avoid exposing it. Refer to the Terraform documentation to learn more about securing your state file.
        /// 
        /// &gt; **Note:** To configure a config at the context level, affecting all subjects created within that context, use `confluentcloud.SubjectConfig` resource and pass in the context name as the `SubjectName`. See the confluentcloud.SubjectConfig` resource documentation for more details.
        /// </summary>
        public readonly string Secret;

        [OutputConstructor]
        private SchemaRegistryClusterConfigCredentials(
            string key,

            string secret)
        {
            Key = key;
            Secret = secret;
        }
    }
}
