// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.ConfluentCloud.Outputs
{

    [OutputType]
    public sealed class SwitchoverEndpointEndpointEndpointFilter
    {
        /// <summary>
        /// The CRN of the network access point, for access-point (PNI) endpoints.
        /// </summary>
        public readonly string? AccessPointCrn;
        /// <summary>
        /// The CRN of the network, for network-based private endpoints.
        /// </summary>
        public readonly string? NetworkCrn;
        /// <summary>
        /// Whether the endpoint is `Private` or `Public`.
        /// </summary>
        public readonly string Type;

        [OutputConstructor]
        private SwitchoverEndpointEndpointEndpointFilter(
            string? accessPointCrn,

            string? networkCrn,

            string type)
        {
            AccessPointCrn = accessPointCrn;
            NetworkCrn = networkCrn;
            Type = type;
        }
    }
}
