// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.ConfluentCloud.Inputs
{

    public sealed class GetClusterLinkKafkaClusterArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The ID of the Kafka cluster to query for the Cluster Link, for example, `lkc-abc123`.
        /// </summary>
        [Input("id", required: true)]
        public string Id { get; set; } = null!;

        public GetClusterLinkKafkaClusterArgs()
        {
        }
        public static new GetClusterLinkKafkaClusterArgs Empty => new GetClusterLinkKafkaClusterArgs();
    }
}
