// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.ConfluentCloud.Inputs
{

    public sealed class GetKafkaClusterEnterpriseInputArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// (Optional Number) The maximum number of Elastic Confluent Kafka Units (eCKUs) that Kafka clusters should auto-scale to. Kafka clusters with "HIGH" availability must have at least two eCKUs. For more details, see [Maximum eCKU requirements](https://docs.confluent.io/cloud/current/clusters/cluster-types.html#minimum-maximum-ecku-requirements).
        /// </summary>
        [Input("maxEcku", required: true)]
        public Input<int> MaxEcku { get; set; } = null!;

        public GetKafkaClusterEnterpriseInputArgs()
        {
        }
        public static new GetKafkaClusterEnterpriseInputArgs Empty => new GetKafkaClusterEnterpriseInputArgs();
    }
}
