// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.ConfluentCloud.Inputs
{

    public sealed class GetKafkaTopicCredentialsArgs : global::Pulumi.InvokeArgs
    {
        [Input("key", required: true)]
        private string? _key;

        /// <summary>
        /// The Kafka API Key.
        /// </summary>
        public string? Key
        {
            get => _key;
            set => _key = value;
        }

        [Input("secret", required: true)]
        private string? _secret;

        /// <summary>
        /// The Kafka API Secret.
        /// 
        /// &gt; **Note:** A Kafka API key consists of a key and a secret. Kafka API keys are required to interact with Kafka clusters in Confluent Cloud. Each Kafka API key is valid for one specific Kafka cluster.
        /// 
        /// !&gt; **Warning:** Terraform doesn't encrypt the sensitive `Credentials` value of the `confluentcloud.KafkaTopic` data source, so you must keep your state file secure to avoid exposing it. Refer to the Terraform documentation to learn more about securing your state file.
        /// </summary>
        public string? Secret
        {
            get => _secret;
            set => _secret = value;
        }

        public GetKafkaTopicCredentialsArgs()
        {
        }
        public static new GetKafkaTopicCredentialsArgs Empty => new GetKafkaTopicCredentialsArgs();
    }
}
