// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.ConfluentCloud.Inputs
{

    public sealed class GetSchemaRulesetArgs : global::Pulumi.InvokeArgs
    {
        [Input("domainRules")]
        private List<Inputs.GetSchemaRulesetDomainRuleArgs>? _domainRules;

        /// <summary>
        /// (Optional List of Blocks) supports the following:
        /// </summary>
        public List<Inputs.GetSchemaRulesetDomainRuleArgs> DomainRules
        {
            get => _domainRules ?? (_domainRules = new List<Inputs.GetSchemaRulesetDomainRuleArgs>());
            set => _domainRules = value;
        }

        [Input("migrationRules")]
        private List<Inputs.GetSchemaRulesetMigrationRuleArgs>? _migrationRules;

        /// <summary>
        /// (Optional List of Blocks) supports the following:
        /// </summary>
        public List<Inputs.GetSchemaRulesetMigrationRuleArgs> MigrationRules
        {
            get => _migrationRules ?? (_migrationRules = new List<Inputs.GetSchemaRulesetMigrationRuleArgs>());
            set => _migrationRules = value;
        }

        public GetSchemaRulesetArgs()
        {
        }
        public static new GetSchemaRulesetArgs Empty => new GetSchemaRulesetArgs();
    }
}
