// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.ConfluentCloud.Inputs
{

    public sealed class KafkaClusterBasicGetArgs : global::Pulumi.ResourceArgs
    {
        public KafkaClusterBasicGetArgs()
        {
        }
        public static new KafkaClusterBasicGetArgs Empty => new KafkaClusterBasicGetArgs();
    }
}
