// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * [![Preview](https://img.shields.io/badge/Lifecycle%20Stage-Preview-%2300afba)](https://docs.confluent.io/cloud/current/api.html#section/Versioning/API-Lifecycle-Policy)
 *
 * > **Warning:** Switchover is a preview feature. Preview features are introduced to gather customer feedback and may change based on that feedback. They are intended for evaluation and non-production use only, and are not covered by Confluent SLAs. Preview features may be discontinued at any time.
 *
 * `confluentcloud.getSwitchoverEndpoints` lists the switchover endpoints in an environment, optionally only those bound to one switchover pair.
 */
export function getSwitchoverEndpoints(args: GetSwitchoverEndpointsArgs, opts?: pulumi.InvokeOptions): Promise<GetSwitchoverEndpointsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("confluentcloud:index/getSwitchoverEndpoints:getSwitchoverEndpoints", {
        "environmentCrn": args.environmentCrn,
        "switchoverPairId": args.switchoverPairId,
    }, opts);
}

/**
 * A collection of arguments for invoking getSwitchoverEndpoints.
 */
export interface GetSwitchoverEndpointsArgs {
    /**
     * The CRN of the environment whose switchover endpoints to list, for example, `crn://confluent.cloud/organization=org-abc/environment=env-abc123`.
     */
    environmentCrn: string;
    /**
     * Only list endpoints bound to this switchover pair, for example, `sw-abc123`.
     */
    switchoverPairId?: string;
}

/**
 * A collection of values returned by getSwitchoverEndpoints.
 */
export interface GetSwitchoverEndpointsResult {
    readonly environmentCrn: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * (Required List of Object) The matching switchover endpoints. Each object exports the same attributes as the `confluentcloud.SwitchoverEndpoint` data source:
     */
    readonly switchoverEndpoints: outputs.GetSwitchoverEndpointsSwitchoverEndpoint[];
    readonly switchoverPairId?: string;
}
/**
 * [![Preview](https://img.shields.io/badge/Lifecycle%20Stage-Preview-%2300afba)](https://docs.confluent.io/cloud/current/api.html#section/Versioning/API-Lifecycle-Policy)
 *
 * > **Warning:** Switchover is a preview feature. Preview features are introduced to gather customer feedback and may change based on that feedback. They are intended for evaluation and non-production use only, and are not covered by Confluent SLAs. Preview features may be discontinued at any time.
 *
 * `confluentcloud.getSwitchoverEndpoints` lists the switchover endpoints in an environment, optionally only those bound to one switchover pair.
 */
export function getSwitchoverEndpointsOutput(args: GetSwitchoverEndpointsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSwitchoverEndpointsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("confluentcloud:index/getSwitchoverEndpoints:getSwitchoverEndpoints", {
        "environmentCrn": args.environmentCrn,
        "switchoverPairId": args.switchoverPairId,
    }, opts);
}

/**
 * A collection of arguments for invoking getSwitchoverEndpoints.
 */
export interface GetSwitchoverEndpointsOutputArgs {
    /**
     * The CRN of the environment whose switchover endpoints to list, for example, `crn://confluent.cloud/organization=org-abc/environment=env-abc123`.
     */
    environmentCrn: pulumi.Input<string>;
    /**
     * Only list endpoints bound to this switchover pair, for example, `sw-abc123`.
     */
    switchoverPairId?: pulumi.Input<string | undefined>;
}
