// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * [![General Availability](https://img.shields.io/badge/Lifecycle%20Stage-General%20Availability-%2345c6e8)](https://docs.confluent.io/cloud/current/api.html#section/Versioning/API-Lifecycle-Policy)
 *
 * `confluentcloud.ProviderIntegrationAuthorization` configures and validates a Cloud Service Provider (CSP) integration created by `confluentcloud.ProviderIntegrationSetup`. This resource transitions the integration from DRAFT to CREATED status and validates the cloud provider setup.
 *
 * > **Note:** This resource will show persistent warnings until the cloud provider setup is complete. For Azure, you must grant admin consent and create a service principal. For GCP, you must configure IAM permissions.
 *
 * ## Example Usage
 *
 * ### Azure Provider Integration Authorization
 *
 * You have two options to complete the Azure setup after creating the authorization resource:
 *
 * ### Option 1: Using Azure Terraform Provider (Recommended for Infrastructure as Code)
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as azuread from "@pulumi/azuread";
 * import * as confluentcloud from "@pulumi/confluentcloud";
 *
 * const azure = new confluentcloud.ProviderIntegrationSetup("azure", {
 *     environment: {
 *         id: environmentId,
 *     },
 *     displayName: "azure-integration",
 *     cloud: "AZURE",
 * });
 * const azureProviderIntegrationAuthorization = new confluentcloud.ProviderIntegrationAuthorization("azure", {
 *     providerIntegrationId: azure.id,
 *     environment: {
 *         id: environmentId,
 *     },
 *     azure: {
 *         customerAzureTenantId: azureTenantId,
 *     },
 * });
 * // Automatically create the service principal using Azure Terraform Provider
 * const confluent = new azuread.index.ServicePrincipal("confluent", {clientId: azureProviderIntegrationAuthorization.azure?.confluentMultiTenantAppId});
 * export const azureAppId = azureProviderIntegrationAuthorization.azure.apply(azure => azure?.confluentMultiTenantAppId);
 * export const servicePrincipalObjectId = confluent.objectId;
 * ```
 *
 * ### Option 2: Using Azure CLI Commands
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as confluentcloud from "@pulumi/confluentcloud";
 *
 * const azure = new confluentcloud.ProviderIntegrationSetup("azure", {
 *     environment: {
 *         id: environmentId,
 *     },
 *     displayName: "azure-integration",
 *     cloud: "AZURE",
 * });
 * const azureProviderIntegrationAuthorization = new confluentcloud.ProviderIntegrationAuthorization("azure", {
 *     providerIntegrationId: azure.id,
 *     environment: {
 *         id: environmentId,
 *     },
 *     azure: {
 *         customerAzureTenantId: azureTenantId,
 *     },
 * });
 * export const azureSetupCommand = azureProviderIntegrationAuthorization.azure.apply(azure => `az ad sp create --id ${azure?.confluentMultiTenantAppId}`);
 * ```
 *
 * ### GCP Provider Integration Authorization
 *
 * You have two options to complete the GCP setup after creating the authorization resource:
 *
 * ### Option 1: Using Google Terraform Provider (Recommended for Infrastructure as Code)
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as confluentcloud from "@pulumi/confluentcloud";
 * import * as google from "@pulumi/google";
 *
 * const gcp = new confluentcloud.ProviderIntegrationSetup("gcp", {
 *     environment: {
 *         id: environmentId,
 *     },
 *     displayName: "gcp-integration",
 *     cloud: "GCP",
 * });
 * const gcpProviderIntegrationAuthorization = new confluentcloud.ProviderIntegrationAuthorization("gcp", {
 *     providerIntegrationId: gcp.id,
 *     environment: {
 *         id: environmentId,
 *     },
 *     gcp: {
 *         customerGoogleServiceAccount: gcpServiceAccount,
 *     },
 * });
 * // Grant IAM permissions using Google Terraform Provider
 * const confluentTokenCreator = new google.index.ProjectIamMember("confluent_token_creator", {
 *     project: gcpProjectId,
 *     role: "roles/iam.serviceAccountTokenCreator",
 *     member: `serviceAccount:${gcpProviderIntegrationAuthorization.gcp?.googleServiceAccount}`,
 *     condition: [{
 *         title: "Confluent Cloud Access",
 *         description: "Allow Confluent Cloud to impersonate the customer service account",
 *         expression: `request.auth.claims.sub == '${gcpProviderIntegrationAuthorization.gcp?.googleServiceAccount}'`,
 *     }],
 * });
 * export const confluentServiceAccount = gcpProviderIntegrationAuthorization.gcp.apply(gcp => gcp?.googleServiceAccount);
 * ```
 *
 * ### Option 2: Using gcloud CLI Commands
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as confluentcloud from "@pulumi/confluentcloud";
 *
 * const gcp = new confluentcloud.ProviderIntegrationSetup("gcp", {
 *     environment: {
 *         id: environmentId,
 *     },
 *     displayName: "gcp-integration",
 *     cloud: "GCP",
 * });
 * const gcpProviderIntegrationAuthorization = new confluentcloud.ProviderIntegrationAuthorization("gcp", {
 *     providerIntegrationId: gcp.id,
 *     environment: {
 *         id: environmentId,
 *     },
 *     gcp: {
 *         customerGoogleServiceAccount: gcpServiceAccount,
 *     },
 * });
 * export const gcpIamCommand = pulumi.all([gcpProviderIntegrationAuthorization.gcp, gcpProviderIntegrationAuthorization.gcp]).apply(([gcpProviderIntegrationAuthorizationGcp, gcpProviderIntegrationAuthorizationGcp1]) => `gcloud projects add-iam-policy-binding YOUR_PROJECT_ID --member="serviceAccount:${gcpProviderIntegrationAuthorizationGcp?.googleServiceAccount}" --role="roles/iam.serviceAccountTokenCreator" --condition="expression=request.auth.claims.sub=='${gcpProviderIntegrationAuthorizationGcp1?.googleServiceAccount}'"`);
 * export const confluentServiceAccount = gcpProviderIntegrationAuthorization.gcp.apply(gcp => gcp?.googleServiceAccount);
 * ```
 *
 * ## Azure Setup Process
 *
 * After applying the Terraform configuration, complete the Azure setup:
 *
 * 1. **Get the multi-tenant app ID** from the Terraform outputs
 * 2. **Grant admin consent** (if you have Global Admin rights):
 * 4. **Grant permissions** in Azure Portal → Enterprise Applications
 * 5. **Re-run `pulumi up`** to validate the connection
 *
 * ## GCP Setup Process
 *
 * After applying the Terraform configuration, complete the GCP setup:
 *
 * 1. **Get the Confluent service account** from the Terraform outputs
 * 2. **Grant IAM permissions** in GCP Console:
 *    - Grant the Confluent service account "Service Account Token Creator" role on your service account
 *    - Grant your service account the necessary permissions (e.g., BigQuery Data Editor)
 * 3. **Re-run `pulumi up`** to validate the connection
 *
 * ## Getting Started
 *
 * The following end-to-end examples might help to get started with `confluentcloud.ProviderIntegrationAuthorization` resource:
 * * provider-integration-azure: Complete Azure Provider Integration setup
 * * provider-integration-gcp: Complete GCP Provider Integration setup
 *
 * ## Import
 *
 * > **Note:** `CONFLUENT_CLOUD_API_KEY` and `CONFLUENT_CLOUD_API_SECRET` environment variables must be set before importing a Provider Integration Authorization.
 *
 * You can import a Provider Integration Authorization by using Environment ID and Provider Integration ID, in the format `<Environment ID>/<Provider Integration ID>`. The following example shows how to import a Provider Integration Authorization:
 *
 * ```sh
 * $ export CONFLUENT_CLOUD_API_KEY="<cloud_api_key>"
 * $ export CONFLUENT_CLOUD_API_SECRET="<cloud_api_secret>"
 * $ pulumi import confluentcloud:index/providerIntegrationAuthorization:ProviderIntegrationAuthorization main env-abc123/cspi-4xg0q
 * ```
 *
 * !> **Warning:** Do not forget to delete terminal command history afterwards for security purposes.
 */
export class ProviderIntegrationAuthorization extends pulumi.CustomResource {
    /**
     * Get an existing ProviderIntegrationAuthorization resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ProviderIntegrationAuthorizationState, opts?: pulumi.CustomResourceOptions): ProviderIntegrationAuthorization {
        return new ProviderIntegrationAuthorization(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'confluentcloud:index/providerIntegrationAuthorization:ProviderIntegrationAuthorization';

    /**
     * Returns true if the given object is an instance of ProviderIntegrationAuthorization.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ProviderIntegrationAuthorization {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ProviderIntegrationAuthorization.__pulumiType;
    }

    /**
     * (Optional Configuration Block) Azure-specific configuration details. It supports the following:
     */
    declare public readonly azure: pulumi.Output<outputs.ProviderIntegrationAuthorizationAzure | undefined>;
    /**
     * Environment objects represent an isolated namespace for your Confluent resources for organizational purposes.
     */
    declare public readonly environment: pulumi.Output<outputs.ProviderIntegrationAuthorizationEnvironment>;
    /**
     * (Optional Configuration Block) GCP-specific configuration details. It supports the following:
     */
    declare public readonly gcp: pulumi.Output<outputs.ProviderIntegrationAuthorizationGcp | undefined>;
    /**
     * The ID of the provider integration to authorize.
     */
    declare public readonly providerIntegrationId: pulumi.Output<string>;

    /**
     * Create a ProviderIntegrationAuthorization resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ProviderIntegrationAuthorizationArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ProviderIntegrationAuthorizationArgs | ProviderIntegrationAuthorizationState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ProviderIntegrationAuthorizationState | undefined;
            resourceInputs["azure"] = state?.azure;
            resourceInputs["environment"] = state?.environment;
            resourceInputs["gcp"] = state?.gcp;
            resourceInputs["providerIntegrationId"] = state?.providerIntegrationId;
        } else {
            const args = argsOrState as ProviderIntegrationAuthorizationArgs | undefined;
            if (args?.environment === undefined && !opts.urn) {
                throw new Error("Missing required property 'environment'");
            }
            if (args?.providerIntegrationId === undefined && !opts.urn) {
                throw new Error("Missing required property 'providerIntegrationId'");
            }
            resourceInputs["azure"] = args?.azure;
            resourceInputs["environment"] = args?.environment;
            resourceInputs["gcp"] = args?.gcp;
            resourceInputs["providerIntegrationId"] = args?.providerIntegrationId;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ProviderIntegrationAuthorization.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ProviderIntegrationAuthorization resources.
 */
export interface ProviderIntegrationAuthorizationState {
    /**
     * (Optional Configuration Block) Azure-specific configuration details. It supports the following:
     */
    azure?: pulumi.Input<inputs.ProviderIntegrationAuthorizationAzure>;
    /**
     * Environment objects represent an isolated namespace for your Confluent resources for organizational purposes.
     */
    environment?: pulumi.Input<inputs.ProviderIntegrationAuthorizationEnvironment>;
    /**
     * (Optional Configuration Block) GCP-specific configuration details. It supports the following:
     */
    gcp?: pulumi.Input<inputs.ProviderIntegrationAuthorizationGcp>;
    /**
     * The ID of the provider integration to authorize.
     */
    providerIntegrationId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a ProviderIntegrationAuthorization resource.
 */
export interface ProviderIntegrationAuthorizationArgs {
    /**
     * (Optional Configuration Block) Azure-specific configuration details. It supports the following:
     */
    azure?: pulumi.Input<inputs.ProviderIntegrationAuthorizationAzure>;
    /**
     * Environment objects represent an isolated namespace for your Confluent resources for organizational purposes.
     */
    environment: pulumi.Input<inputs.ProviderIntegrationAuthorizationEnvironment>;
    /**
     * (Optional Configuration Block) GCP-specific configuration details. It supports the following:
     */
    gcp?: pulumi.Input<inputs.ProviderIntegrationAuthorizationGcp>;
    /**
     * The ID of the provider integration to authorize.
     */
    providerIntegrationId: pulumi.Input<string>;
}
